stages:
  - build

image: node

before_script:
  - npm install -g vsce
  - npm install

build:
  stage: build
  script:
    - npm run lint
    - VERSION=$(node -p "require('./package.json').version")
    - npx vsce package -o vscode-rhoas-${VERSION}-${CI_PIPELINE_IID}.vsix
  artifacts:
    paths:
      - "*.vsix"
  tags:
    - shared
